// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: view_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const viewChirp = `-- name: ViewChirp :one

SELECT id, created_at, updated_at, body, user_id
FROM chirps
WHERE id=$1
`

func (q *Queries) ViewChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, viewChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
